# Generated by Django 5.2.7 on 2025-10-21 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMRun",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("prompt", models.TextField()),
                ("plan", models.JSONField()),
                ("state", models.CharField(default="CREATED", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("preview_url", models.URLField(blank=True, null=True)),
                ("pr_url", models.URLField(blank=True, null=True)),
                (
                    "requester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("op", models.CharField(max_length=100)),
                ("params", models.JSONField()),
                ("diff", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_llm.llmrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file_path", models.CharField(max_length=255)),
                ("hash", models.CharField(max_length=64)),
                ("diff_text", models.TextField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_llm.task",
                    ),
                ),
            ],
        ),
    ]
