# Generated by Django 5.2.7 on 2025-10-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_llm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(max_length=100)),
                ("level", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
