# Generated by Django 5.2.7 on 2025-10-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_llm", "0002_llmlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrun",
            name="run_type",
            field=models.CharField(
                choices=[("USER", "User Initiated"), ("AI", "AI Suggested")],
                default="USER",
                max_length=4,
            ),
        ),
    ]
